const GENERIC_HANDLER_GOERLI = process.env.GENERIC_HANDLER_GOERLI || "0x0";
const GOERLI_TESTNET_ADDRESS =
  process.env.GOERLI_TESTNET_ADDRESS || GENERIC_HANDLER_GOERLI;
const DEST_GAS_LIMIT = process.env.DEST_GAS_LIMIT || 8000000;
module.exports = { GOERLI_TESTNET_ADDRESS, DEST_GAS_LIMIT };
